production:
  adapter: postgresql
  encoding: unicode
  database: LetsDoIt
  pool: 5
  username: panda3
  password: sampleapp


development:
  adapter: postgresql
  encoding: unicode
  database: LetsDoIt
  pool: 5
  username: panda3
  password: sampleapp

test:
  adapter: postgresql
  encoding: unicode
  database: LetsDoIt
  pool: 5
  username: panda3
  password: sampleapp