production:
  adapter: postgresql
  encoding: unicode
  database: lets_do_it
  pool: 5
  username: panda3
  password: sampleapp


development:
  adapter: postgresql
  encoding: unicode
  database: lets_do_it_development
  pool: 5
  username: panda3
  password: sampleapp

test:
  adapter: postgresql
  encoding: unicode
  database: lets_do_it_test
  pool: 5
  username: panda3
  password: sampleapp